#include <wordbase.h>

char *gpszWordBase[] = {
    "incrivelmente",
    "desenvolvimento",
    "representativo",
    "comportamento",
    "relacionamento",
    "multiplicidade",
    "extraordinario",
    "desnecessario",
    "transcendental",
    "personalidade",
    "indestrutivel",
    "aperfeicoamento",
    "caracteristica",
    "estabelecimento",
    "incompreensivel",
    "reconhecimento",
    "abstracionismo",
    "manipulacao",
    "instrumentalizacao",
    "concretizacao",
    "irreversivel",
    "inconstitucional",
    "territorialidade",
    "internacionalizacao",
    "responsabilidade",
    "formalizacao",
    "horrivel",
    "desastrosa",
    "conceitual",
    "compatibilidade",
    "inseguranca",
    "disponibilidade",
    "documentacao",
    "instrumentacao",
    "inflexibilidade",
    "previsibilidade",
    "comunicabilidade",
    "exclusividade",
    "contrariedade",
    "posterior",
    "subjetividade",
    "reconstrucao",
    "desconstrucao",
    "obrigatoria",
    "injustificavel",
    "essencial",
    "inapropriada",
    "completa",
    "efetiva",
    "permanente",
    "experimental",
    "metodologica",
    "estruturada",
    "seletiva",
    "progressiva",
    "transitoria",
    "fisica",
    "politica",
    "psicologica",
    "comercial",
    "ambiental",
    "potencial",
    NULL
  };
int giCurrWord = 0;

char *pszGetNextWord() {
  if ( gpszWordBase[giCurrWord+1] == NULL )
    giCurrWord = 0;
    
  return gpszWordBase[giCurrWord++];
}
